name: build-and-publish
on:
  push:
    tags:
      - 'v*.*.*'    # run only on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build & publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist
