name: Build & Publish

on:
    push:
        tags:
            - "v*.*.*" # run when you push a tag like v1.2.3

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Build React renderer
              run: npm run build:react

            - name: Package & Publish
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npm run dist:deb
